### ISSUE TITLE
Automate PRISM_HOME and STAMINA_HOME in staminarc

### ISSUE THREAD

**Issue by zgzn** [fluentverification/stamina#17]
Currently, one has to manually set up the .staminarc file located under the user's home directory,  if STAMINA or PRISM is installed in a directory other than the user's home directory (such as /opt/verificationTools/stamina). It would be nice to set up a script to do this. Or at least print out a message to the user in this situation to remind them to set it up manually, after they install STAMINA.

**Comment by ifndefJOSH** [comment]
Install script in commit 418655d03233a022e0b7e2b5af9fc897ec0199f5 in the dev2 branch should do this

**Comment by ifndefJOSH** [comment]
Merged `master` and `dev2` branch to reflect this change
