### ISSUE TITLE
Incorrect Results for `case-studies/Tandem/tandem_c_2047_T_0.25.prism` when early termination optimization is disabled

### ISSUE THREAD

**Issue by ifndefJOSH** [fluentverification/stamina#18]
There are different results (not just wider window, but completely different results) on the model `case-studies/Tandem/tandem_c_2047_T_0.25.prism` when we have early termination of a path based on whether it satisfies the CSL property or not vs when that optimization is commented out. This should not be happening, as either case P_actual should be bounded within Pmin and Pmax

**Comment by zgzn** [comment]
This was actually due to code commented out in the source. Turning off this optimization using the command option gives the correct result.
