### ISSUE TITLE
Be able to check a specific property instead of all of them

### ISSUE THREAD

**Issue by brettjepsen** [fluentverification/stamina#5]
If a props file has more than 1 property, it checks them all, sometimes we just want to check only 1 of them.

**Comment by zgzn** [comment]
Yes, this is a useful feature to have. For STAMINA with property guided state expansion, it only work with one non-nested bounded until property. We can have a command line option to specify which property from a property file a user chooses to check and pass this option to STAMINA.

**Comment by zgzn** [comment]
@brettjepsen The following example shows how to load a model from a file and model check some properties either from a file or specified as a string, and possibly involving constants: https://github.com/prismmodelchecker/prism-api/blob/master/src/demos/ModelCheckFromFiles.java

**Comment by brettjepsen** [comment]
Done
